### PR TITLE
Implementation of LCD methods

### PR DESCRIPTION
**Pull request by haeberle**
Implementation of the M5Stack methods. 

Pls review the structure and native code calls and provide me feedback

- Addresses nanoframework/Home#519

### CODE REVIEW

**Comment by josesimoes** [comment]
> I'm thinking to define all the methods as static, because the LCD it is a single resource.

Guess that makes sense…

> Is there a need to make the managed code thread save ?

That's a great question. And being thread safe is a must! But I think it can be acomplished at native level. The line should be drawn at the access to the SPI bus. That's supposed to be already access protected by semaphore (or equivalent depending on the platform). All the rest should be OK. 
This makes it much simpler than having to wrap all native calls with locks.

The only exception that comes to mind would a common buffer to dump data to the LCD (if there is one). If the need rises we can accommodate that.

**Comment by haeberle** [comment]
I did an update of the discussed points, but leave the color enum as defined, lets revise if needed. 

About the buffer, currently the LCD class does not support such buffer in the managed code, lets see what is needed for further improvements and requirements also from the WPF stream.

One thing I have to ask: do I have to create a new PR for each new commit ?

**Comment by josesimoes** [comment]
> do I have to create a new PR for each new commit ? 

Nope! You're doing just fine with this.
As this is an "ongoing" matter, all commits (related with this) belong in this PR.

A suggestion to you: you should be working on a local branch other than develop. This way you can have it independent, merge the changes from upstream only when needed. And (this is big) you always have a "safe" place to return to in case something goes south with merges, messed up code, etc.

Take a look at our docs, about the recommended git workflow. Anyways you can find a bunch of reading and tutorials about this.

**Comment by haeberle** [comment]
Question about the next steps. Do you need some thing from my side to move forward ?

**Comment by josesimoes** [comment]
@haeberle it's just that, for some reason, I missed the update from GitHub that you've pushed more commits to this… Apologies for taking so long. 
It's OK now.

**Comment by josesimoes** [comment]
Just waiting for the native part.

**Pull request closed without merging**
